export const LabelStyle = Object.freeze({
	FILLED_EXTRA: 'filledExtra',
	FILLED: 'filled',
	FILLED_ALERT: 'filledAlert',
	FILLED_WARNING: 'filledWarning',
	FILLED_SUCCESS: 'filledSuccess',
	FILLED_NO_ACCENT: 'filledNoAccent',
	FILLED_INVERTED: 'filledInverted',
	FILLED_ALERT_INVERTED: 'filledAlertInverted',
	FILLED_WARNING_INVERTED: 'filledWarningInverted',
	FILLED_SUCCESS_INVERTED: 'filledSuccessInverted',
	FILLED_NO_ACCENT_INVERTED: 'filledNoAccentInverted',
	TINTED: 'tinted',
	TINTED_SUCCESS: 'tintedSuccess',
	TINTED_WARNING: 'tintedWarning',
	TINTED_NO_ACCENT: 'tintedNoAccent',
	COLLAB: 'collab',
	OUTLINE_NO_ACCENT: 'outlineNoAccent',
});
