import { Disk, DiskCompact } from 'ui.icon-set.api.core';

export const DiskIconType = Object.freeze({
	png: 'png',
	jpg: 'jpg',
	jpeg: 'jpeg',
	gif: 'gif',
	bmp: 'bmp',
	webp: 'webp',
	svg: 'svg',
	xml: 'xml',
	pdf: 'pdf',
	xls: 'xls',
	xlsx: 'xlsx',
	doc: 'doc',
	docx: 'docx',
	txt: 'txt',
	ppt: 'ppt',
	pptx: 'pptx',
	rar: 'rar',
	zip: 'zip',
	gzip: 'gzip',
	gz: 'gz',
	archive: 'archive',
	folder: 'folder',
	folderGroup: 'folderGroup',
	folderShared: 'folderShared',
	folderCollab: 'folderCollab',
	folder24: 'folder24',
	folderPerson: 'folderPerson',
	// Добавляем видео типы
	mp4: 'mp4',
	avi: 'avi',
	mov: 'mov',
	wmv: 'wmv',
	webm: 'webm',
	mkv: 'mkv',
	video: 'video',
	file: 'file',
});

export const TypeIcon = Object.freeze({
	[DiskIconType.file]: Disk.EMPTY,
	[DiskIconType.png]: Disk.IMAGE,
	[DiskIconType.jpg]: Disk.IMAGE,
	[DiskIconType.jpeg]: Disk.IMAGE,
	[DiskIconType.gif]: Disk.IMAGE,
	[DiskIconType.bmp]: Disk.IMAGE,
	[DiskIconType.webp]: Disk.IMAGE,
	[DiskIconType.svg]: Disk.SVG,
	[DiskIconType.xml]: Disk.XML,
	[DiskIconType.pdf]: Disk.PDF,
	[DiskIconType.xls]: Disk.XLS,
	[DiskIconType.xlsx]: Disk.XLSX,
	[DiskIconType.doc]: Disk.DOC,
	[DiskIconType.docx]: Disk.DOCX,
	[DiskIconType.txt]: Disk.TXT,
	[DiskIconType.ppt]: Disk.PPT,
	[DiskIconType.pptx]: Disk.PPTX,
	[DiskIconType.rar]: Disk.RAR,
	[DiskIconType.zip]: Disk.ZIP,
	[DiskIconType.gzip]: Disk.ARCHIVE,
	[DiskIconType.gz]: Disk.ARCHIVE,
	[DiskIconType.archive]: Disk.ARCHIVE,
	[DiskIconType.folder]: Disk.FOLDER,
	[DiskIconType.folderGroup]: Disk.FOLDER_GROUP,
	[DiskIconType.folderShared]: Disk.FOLDER_SHARED,
	[DiskIconType.folderCollab]: Disk.FOLDER_COLLAB,
	[DiskIconType.folder24]: Disk.FOLDER_24,
	[DiskIconType.folderPerson]: Disk.FOLDER_PERSON,
	[DiskIconType.mp4]: Disk.VIDEO || Disk.FILE,
	[DiskIconType.avi]: Disk.VIDEO || Disk.FILE,
	[DiskIconType.mov]: Disk.VIDEO || Disk.FILE,
	[DiskIconType.wmv]: Disk.VIDEO || Disk.FILE,
	[DiskIconType.webm]: Disk.VIDEO || Disk.FILE,
	[DiskIconType.mkv]: Disk.VIDEO || Disk.FILE,
	[DiskIconType.video]: Disk.VIDEO || Disk.FILE,
});

export const CompactTypeIcon = Object.freeze({
	[DiskIconType.file]: Disk.EMPTY,
	[DiskIconType.png]: DiskCompact.IMAGE,
	[DiskIconType.jpg]: DiskCompact.IMAGE,
	[DiskIconType.jpeg]: DiskCompact.IMAGE,
	[DiskIconType.gif]: DiskCompact.IMAGE,
	[DiskIconType.bmp]: DiskCompact.IMAGE,
	[DiskIconType.webp]: DiskCompact.IMAGE,
	[DiskIconType.svg]: DiskCompact.IMAGE,
	[DiskIconType.xml]: DiskCompact.XML,
	[DiskIconType.pdf]: DiskCompact.PDF,
	[DiskIconType.xls]: DiskCompact.XLS,
	[DiskIconType.xlsx]: DiskCompact.XLSX,
	[DiskIconType.doc]: DiskCompact.DOC,
	[DiskIconType.docx]: DiskCompact.DOCX,
	[DiskIconType.txt]: DiskCompact.TXT,
	[DiskIconType.ppt]: DiskCompact.PPT,
	[DiskIconType.pptx]: DiskCompact.PPTX,
	[DiskIconType.rar]: DiskCompact.RAR,
	[DiskIconType.zip]: DiskCompact.ZIP,
	[DiskIconType.gzip]: DiskCompact.ARCHIVE,
	[DiskIconType.gz]: DiskCompact.ARCHIVE,
	[DiskIconType.archive]: DiskCompact.ARCHIVE,
	[DiskIconType.folder]: DiskCompact.FOLDER,
	[DiskIconType.folderGroup]: DiskCompact.FOLDER_GROUP,
	[DiskIconType.folderShared]: DiskCompact.FOLDER_SHARED,
	[DiskIconType.folderCollab]: DiskCompact.FOLDER_COLLAB,
	[DiskIconType.folder24]: DiskCompact.FOLDER_24,
	[DiskIconType.folderPerson]: DiskCompact.FOLDER_PERSON,
	[DiskIconType.mp4]: DiskCompact.VIDEO || DiskCompact.FILE,
	[DiskIconType.avi]: DiskCompact.VIDEO || DiskCompact.FILE,
	[DiskIconType.mov]: DiskCompact.VIDEO || DiskCompact.FILE,
	[DiskIconType.wmv]: DiskCompact.VIDEO || DiskCompact.FILE,
	[DiskIconType.webm]: DiskCompact.VIDEO || DiskCompact.FILE,
	[DiskIconType.mkv]: DiskCompact.VIDEO || DiskCompact.FILE,
	[DiskIconType.video]: DiskCompact.VIDEO || DiskCompact.FILE,
});
